name: Publish Docker
on:
  push:
    branches:
      - lunar
  schedule:
    - cron: '0 3 * * 0' # Weekly on Sundays at 03:00

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v3
      - run:  bash thine.sh
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: 31482281/ubuntu
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: ${{ github.event_name != 'schedule' }}
          dockerfile: Dockerfile
          buildoptions: --no-cache --compress --squash
          tags: "latest,lunar"
